---
title: "Post-Graduation Income"
toc: true
toc-depth: 4
toc-location: right
sidebar: false
---

<!-- ::: {.callout-note icon="terminal" title="Try it live!"} -->
<!-- Use Binder to explore and run this dataset and analysis interactively in your browser with `R`. Ideal for students and instructors to run, modify, and test the analysis in a live JupyterLab environment—no setup needed.  -->

<!-- 👉 [Launch on Binder](https://mybinder.org/v2/gh/jadeeechen/diversedata-notebooks/HEAD?urlpath=lab/tree/wildfire.ipynb){target="_blank" rel="noopener"} -->

<!-- ::: -->

## About the Data

This dataset contains information on median income of Canadian students two years after graduation, compiled by Statistics Canada under the Open Government Licence – Canada. 


** DESCRIPTION TO COME **


### Download

<div class="button-container">
  <a href="../../data/clean/postgradincome.csv" download class="download-button">
    Download CSV
  </a>
</div>

### Metadata

<div class="description-grid">
  <div class="field-label">CSV Name</div><div class="field-value">postgradincome.csv</div>
  <div class="field-label">Dataset Characteristics</div><div class="field-value">Multivariate</div>
  <div class="field-label">Subject Area</div><div class="field-value">Equity, Education, Income Disparity</div>
  <div class="field-label">Associated Tasks</div><div class="field-value">Comparative Analysis, ...</div>
  <div class="field-label">Feature Type</div><div class="field-value">Categorical, Numeric</div>
  <div class="field-label">Instances</div><div class="field-value">16,636 records</div>
  <div class="field-label">Features</div><div class="field-value">9</div>
  <div class="field-label">Has Missing Values?</div><div class="field-value">No</div>
</div>

### Variables

::: {.table-container}
::: {.styled-table}

| Variable Name                  | Role     | Type        | Description         | Units         | Missing Values |
|--------------------------------|----------|-------------|---------------------------------------------------------------------------------------------------|---------------|----------------|
| `year`         | ID       | Integer     | Year    | Year          | No             |
| `location`     | Feature       | Categorical     | Geographical location, e.g. "Canada", "Quebec", etc.| - | No |
| `educational_qualification`  | Feature    | Categorical     | Type of educational degree received, e.g. "Undergraduate degree"    | -      | No     |
| `field_of_study`    | Feature       | Categorical     | Topic studied, e.g. "Health and related fields"  | -  | No     |
| `gender`    | Feature       | Categorical     | "Woman", "Man", or "Total"    | -       | No             |
| `age_group`  | Feature       | Categorial     | Range of ages, e.g. "15 to 34 years"    | -      | No       |
| `population_group`   | Feature       | Categorical     | Population group, e.g. "South Asian", "Black", "Visible minority population"    | -          | No             |
| `median_income` | Feature       | Integer     | Median reported income    | 2024 constant Canadian dollars     | No         |
| `number_graduates` | Feature       | Integer     | Number of graduates who reported income    | -    | No         |

:::
:::

{{< include ../notebooks/postgradincome.qmd >}} 

## Attribution

Data sourced from Statistics Canada via the Government of Canada's Open Government Portal, available under an [Open Government Licence - Canada](https://open.canada.ca/en/open-government-licence-canada). Original dataset: [Characteristics and median employment income of Canadian postsecondary graduates two years after graduation, by visible minority group, educational qualification and field of study (primary groupings)](https://open.canada.ca/data/en/dataset/92554b64-fc13-427f-bbb2-f16b3436759c).

